package ma.spring.notificationservice.model;

public enum NotificationType {
    REGISTRATION_SUBMITTED,
    REGISTRATION_APPROVED_BY_DIRECTOR,
    REGISTRATION_REJECTED_BY_DIRECTOR,
    REGISTRATION_APPROVED_BY_ADMIN,
    REGISTRATION_REJECTED_BY_ADMIN,
    DEFENSE_SUBMITTED,
    DEFENSE_REQUEST_SUBMITTED,
    DEFENSE_APPROVED,
    DEFENSE_REJECTED,
    DEFENSE_SCHEDULED,
    DEFENSE_COMPLETED,
    REMINDER_CAMPAIGN_ENDING,
    REMINDER_DOCUMENTS_MISSING,
    SYSTEM_ALERT
}